version: '3.8'
services:
  dash-app:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      - NVIDIA_VISIBLE_DEVICES=all