services:
  dash-app:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    deploy:
      resources:
        limits:
          cpus: "4"  # Use 4 of 8 cores
          memory: 16g  # Cap at 16 GB RAM