version: '3.8'
services:
  trading_env:
    build:
      context: .
      dockerfile: Dockerfile
    image: trading_env:latest
    ports:
      - "8050:8050"  # Dash app port
    volumes:
      - .:/app  # Mount project directory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]  # For ROCm GPU access
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.0  # For RX 7800 XT
    command: python trading_dashboard.py