version: '3.8'

services:
  trading-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-dashboard
    ports:
      - "8050:8050"
    volumes:
      - ./data:/home/madbob10/Dash/data
      # For development (uncomment to map source files for live editing)
      # - ./backtestrocm3.py:/app/backtestrocm3.py
      # - ./datalinux2.py:/app/datalinux2.py
      # - ./trading_dashboard.py:/app/trading_dashboard.py
    environment:
      - PYTHONUNBUFFERED=1
    # Optional: GPU passthrough for ROCm (uncomment if needed)
    # devices:
    #  - /dev/kfd:/dev/kfd
    #  - /dev/dri:/dev/dri
    restart: unless-stopped